"""Operational metrics — what the system indexed, how fast it answers, how
accurate it is, and what humans said about it.

Everything here is computed from artifacts the system already produces: the
index itself, `fixtures/eval-history.jsonl` (written by `eval --log`), and
the local query and feedback logs. Nothing is estimated and nothing is
generated by a model — if a number is missing it is reported as missing
rather than filled in, because the point of this surface is that the
accuracy claims are checkable.
"""

from __future__ import annotations

import json
import sqlite3
from pathlib import Path

MAX_LOG_LINES = 20_000  # a bounded tail keeps the endpoint cheap on big logs


def _tail_jsonl(path: Path, limit: int = MAX_LOG_LINES) -> list[dict]:
    if not path.exists():
        return []
    rows: list[dict] = []
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines()[-limit:]:
        line = line.strip()
        if not line:
            continue
        try:
            obj = json.loads(line)
        except json.JSONDecodeError:
            continue  # torn write; never fatal
        if isinstance(obj, dict):
            rows.append(obj)
    return rows


def _percentile(values: list[float], pct: float) -> float | None:
    if not values:
        return None
    ordered = sorted(values)
    idx = min(len(ordered) - 1, max(0, round((pct / 100) * (len(ordered) - 1))))
    return round(ordered[idx], 1)


def health(conn: sqlite3.Connection) -> dict:
    docs = conn.execute("SELECT COUNT(*) n FROM documents").fetchone()["n"]
    chunks = conn.execute("SELECT COUNT(*) n FROM chunks").fetchone()["n"]
    size = conn.execute("SELECT COALESCE(SUM(size), 0) n FROM documents").fetchone()["n"]
    last = conn.execute("SELECT MAX(indexed_at) t FROM documents").fetchone()["t"]
    by_type = [
        dict(r)
        for r in conn.execute(
            "SELECT filetype, COUNT(*) docs FROM documents "
            "GROUP BY filetype ORDER BY docs DESC, filetype"
        )
    ]
    empty = conn.execute(
        "SELECT COUNT(*) n FROM documents d "
        "WHERE NOT EXISTS (SELECT 1 FROM chunks c WHERE c.doc_id = d.id)"
    ).fetchone()["n"]
    return {
        "documents": docs,
        "chunks": chunks,
        "bytes": size,
        "last_indexed": last,
        "by_type": by_type,
        # A document that produced no chunks is indexed but unsearchable —
        # worth surfacing rather than hiding inside a healthy-looking count.
        "documents_without_chunks": empty,
        "avg_chunks_per_doc": round(chunks / docs, 1) if docs else 0,
    }


def accuracy(history_path: Path, db_name: str | None = None) -> dict:
    """Latest eval run and its trend, straight from the logged history."""
    rows = [r for r in _tail_jsonl(history_path) if "mrr" in r]
    if db_name:
        scoped = [r for r in rows if r.get("db") == db_name]
        # Fall back to every run rather than showing nothing when the active
        # database has never been scored.
        rows = scoped or rows
    if not rows:
        return {"available": False}
    latest = rows[-1]
    total = latest.get("questions") or 0
    series = [
        {
            "ts": r.get("ts", ""),
            "label": r.get("label", ""),
            "hit_at_1": round((r.get("hit_at_1") or 0) / r["questions"], 3) if r.get("questions") else 0,
            "hit_at_k": round((r.get("hit_at_k") or 0) / r["questions"], 3) if r.get("questions") else 0,
            "mrr": r.get("mrr", 0),
        }
        for r in rows[-12:]
    ]
    return {
        "available": True,
        "ts": latest.get("ts", ""),
        "label": latest.get("label", ""),
        "fixtures": latest.get("fixtures", ""),
        "db": latest.get("db", ""),
        "questions": total,
        "k": latest.get("k", 5),
        "hit_at_1": round((latest.get("hit_at_1") or 0) / total, 3) if total else 0,
        "hit_at_k": round((latest.get("hit_at_k") or 0) / total, 3) if total else 0,
        "mrr": latest.get("mrr", 0),
        "runs": len(rows),
        "series": series,
    }


def performance(query_log: Path) -> dict:
    rows = _tail_jsonl(query_log)
    searches = [r for r in rows if r.get("kind") != "doc" and "latency_ms" in r]
    opens = [r for r in rows if r.get("kind") == "doc"]
    latencies = [float(r["latency_ms"]) for r in searches if isinstance(r.get("latency_ms"), (int, float))]
    empty = sum(1 for r in searches if not r.get("hits"))
    return {
        "searches": len(searches),
        "source_opens": len(opens),
        "median_ms": _percentile(latencies, 50),
        "p95_ms": _percentile(latencies, 95),
        "zero_hit_rate": round(empty / len(searches), 3) if searches else 0,
        "recent": [
            {"ts": r.get("ts", ""), "latency_ms": r.get("latency_ms"), "hits": r.get("hits", 0)}
            for r in searches[-30:]
        ],
    }


def feedback_loop(feedback_log: Path, promoted: Path | None = None) -> dict:
    """The human-in-the-loop signal: votes in, fixtures out."""
    rows = _tail_jsonl(feedback_log)
    up = sum(1 for r in rows if r.get("vote") == "up")
    down = sum(1 for r in rows if r.get("vote") == "down")
    by_doc: dict[str, dict] = {}
    for r in rows:
        path = str(r.get("path") or "")
        if not path:
            continue
        entry = by_doc.setdefault(path, {"path": path, "up": 0, "down": 0})
        if r.get("vote") == "up":
            entry["up"] += 1
        elif r.get("vote") == "down":
            entry["down"] += 1
    ranked = sorted(by_doc.values(), key=lambda d: (d["up"] + d["down"]), reverse=True)[:5]
    promoted_count = len(_tail_jsonl(promoted)) if promoted and promoted.exists() else 0
    total = up + down
    return {
        "up": up,
        "down": down,
        "total": total,
        "helpful_rate": round(up / total, 3) if total else None,
        "promoted_fixtures": promoted_count,
        # Upvotes not yet turned into fixtures — the actionable backlog of
        # the self-improvement loop.
        "pending_promotion": max(0, up - promoted_count),
        "by_document": ranked,
    }


def collect(
    conn: sqlite3.Connection,
    history_path: Path,
    query_log: Path,
    feedback_log: Path,
    promoted: Path | None = None,
    db_name: str | None = None,
) -> dict:
    return {
        "health": health(conn),
        "accuracy": accuracy(history_path, db_name),
        "performance": performance(query_log),
        "feedback": feedback_loop(feedback_log, promoted),
    }
